export const API_ENDPOINT = 'https://5b758f56deca780014ec9fc7.mockapi.io/subscription'

export const FETCH_SUBSCRIPTION_REQUEST = 'FETCH_SUBSCRIPTION_REQUEST'
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS'
export const FETCH_SUBSCRIPTION_FAILED = 'FETCH_SUBSCRIPTION_FAILED'
